version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: |
            apt-get update
            apt-get install -y g++ make ca-certificates
      - run:
          name: Make program
          command: |
            make all
      - store_artifacts:
          path: dist
      - run:
          name: Run tests
          command: |
            apt-get install -y python3
            make test
